Repository improbable-eng/ansible-buildkite-agent, pull requests merged in 2021-01, with the labels that each got.

#61 Fix yamllint issues
  .yamllint.yaml
  defaults/main.yml
  handlers/main.yml
Labels: size/L

#60 Add configuration to specify where brew is installed
  CHANGELOG.md
  README.md
  defaults/main.yml
  handlers/main.yml
Labels: size/XS

#62 Bump CHANGELOG for 4.1.0 release
  CHANGELOG.md
Labels: size/XS

#64 Improve yamllint configuration to make it less aggressive
  .yamllint.yaml
  handlers/main.yml
Labels: size/M

#65 Full repo lint to apply new lint configurations for the sake of consistency.
  .travis.yml
  defaults/main.yml
  examples/site.yml
  meta/main.yml
  tasks/install-on-Darwin.yml
  tasks/install-on-Debian.yml
  tasks/install-on-Windows.yml
  tasks/main.yml
Labels: size/XL
